# source = ~/.config/hypr/conf/monitors/nwg-displays.conf
# Main Monitor (HKM 32") - Set to max refresh rate (180Hz)
monitor = DP-1, 2560x1440@180, 0x0, 1

# Secondary Monitor (Samsung 24") - Positioned to the right and slightly down
# Offset calculation: 2560 (width of DP-1) and ~300px down to match physical alignment
monitor = HDMI-A-1, 1920x1080@100, 2560x300, 1
